# Generated by Django 2.2.7 on 2019-11-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stitle', models.CharField(max_length=100)),
                ('sbody', models.TextField()),
                ('PicImg', models.ImageField(upload_to='', verbose_name='blog_pictures')),
                ('dDate', models.DateTimeField(auto_now_add=True)),
                ('sAuthor', models.CharField(max_length=100)),
            ],
        ),
    ]
