# Generated by Django 2.2.7 on 2019-11-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='Post_ID',
            field=models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
